# Generated by Django 5.1.1 on 2024-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_customuser_options_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pictures/DefaulUser.jpg', null=True, upload_to='media/profile_pictures/'),
        ),
    ]
