# Generated by Django 5.1.1 on 2024-10-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/Default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
